CREATE TABLE IF NOT EXISTS biliclaw.dim_comment
(
    rpid UInt64 COMMENT '评论ID',
    rpid_str String COMMENT '评论ID字符串',
    oid UInt64 COMMENT '目标ID(视频aid)',
    oid_str String COMMENT '目标ID字符串',
    `type` UInt8 COMMENT '评论类型(1=视频)',
    root UInt64 COMMENT '根评论ID(0=一级评论)',
    root_str String COMMENT '根评论ID字符串',
    parent UInt64 COMMENT '父评论ID(0=一级评论)',
    parent_str String COMMENT '父评论ID字符串',
    dialog UInt64 COMMENT '对话ID',
    dialog_str String COMMENT '对话ID字符串',
    `count` UInt32 COMMENT '回复总数',
    rcount UInt32 COMMENT '显示的回复数',
    `like` UInt32 COMMENT '点赞数',
    state Int8 COMMENT '评论状态',
    attr UInt32 COMMENT '评论属性',
    fansgrade UInt8 COMMENT '粉丝等级',
    action UInt8 COMMENT '当前用户操作状态',
    ctime UInt32 COMMENT '评论创建时间戳',
    content_message String COMMENT '评论内容',
    content_max_line UInt8 COMMENT '最大显示行数',
    mid UInt64 COMMENT '评论者UID',
    mid_str String COMMENT '评论者UID字符串',
    member_uname String COMMENT '评论者昵称',
    member_sex String COMMENT '评论者性别',
    member_sign String COMMENT '评论者签名',
    member_avatar String COMMENT '评论者头像URL',
    member_rank String COMMENT '评论者等级排名',
    member_level UInt8 COMMENT '评论者等级',
    member_is_senior_member UInt8 COMMENT '是否硬核会员',
    member_vip_type UInt8 COMMENT '评论者VIP类型(0=无,1=月度,2=年度)',
    member_vip_status UInt8 COMMENT '评论者VIP状态',
    member_vip_due_date UInt64 COMMENT '评论者VIP到期时间戳',
    member_vip_label_text String COMMENT '评论者VIP标签文本',
    member_vip_theme_type UInt8 COMMENT '评论者VIP主题类型',
    member_nickname_color String COMMENT '评论者昵称颜色',
    member_official_type Int8 COMMENT '评论者认证类型(-1=无)',
    member_official_desc String COMMENT '评论者认证描述',
    member_pendant_pid UInt32 COMMENT '评论者头像框ID',
    member_pendant_name String COMMENT '评论者头像框名称',
    member_nameplate_nid UInt32 COMMENT '评论者勋章ID',
    member_nameplate_name String COMMENT '评论者勋章名称',
    member_nameplate_level String COMMENT '评论者勋章等级',
    member_sailing_cardbg_id UInt32 COMMENT '评论者卡片背景ID',
    member_sailing_cardbg_name String COMMENT '评论者卡片背景名称',
    member_sailing_fan_is_fan UInt8 COMMENT '是否是粉丝',
    member_sailing_fan_number UInt32 COMMENT '粉丝编号',
    member_sailing_fan_name String COMMENT '粉丝团名称',
    member_is_contractor UInt8 COMMENT '是否是承包者',
    member_contract_desc String COMMENT '承包描述',
    up_action_like UInt8 COMMENT 'UP主是否点赞',
    up_action_reply UInt8 COMMENT 'UP主是否回复',
    reply_control_sub_reply_entry_text String COMMENT '子回复入口文本',
    reply_control_sub_reply_title_text String COMMENT '子回复标题文本',
    reply_control_time_desc String COMMENT '评论时间描述',
    folder_has_folded UInt8 COMMENT '是否有折叠',
    folder_is_folded UInt8 COMMENT '是否被折叠',
    invisible UInt8 COMMENT '是否不可见',
    reply_control_support_share UInt8 COMMENT '是否支持分享',
    etl_time DateTime DEFAULT now() COMMENT 'ETL处理时间'
)
ENGINE = ReplacingMergeTree(etl_time)
ORDER BY (rpid, oid)
SETTINGS index_granularity = 8192
COMMENT 'B站评论维度表';
