CREATE TABLE kafka_account_source (
    card ROW<
        mid STRING,
        name STRING,
        sex STRING,
        sign STRING,
        face STRING,
        `rank` STRING,
        birthday STRING,
        level_info ROW<current_level INT>,
        pendant ROW<pid INT, name STRING>,
        nameplate ROW<nid INT, name STRING, level STRING, `condition` STRING>,
        Official ROW<role INT, title STRING, `desc` STRING, `type` INT>,
        official_verify ROW<`type` INT, `desc` STRING>,
        vip ROW<
            `type` INT,
            status INT,
            due_date BIGINT,
            vip_pay_type INT,
            theme_type INT,
            label ROW<text STRING>,
            nickname_color STRING,
            role INT,
            vipType INT,
            vipStatus INT
        >,
        is_senior_member INT,
        fans INT,
        friend INT,
        attention INT
    >,
    space ROW<
        s_img STRING,
        l_img STRING
    >,
    following BOOLEAN,
    archive_count INT,
    article_count INT,
    follower INT,
    like_num INT
) WITH (
    'connector' = 'kafka',
    'topic' = 'claw_account',
    'properties.bootstrap.servers' = 'kafka:29092',
    'properties.group.id' = 'flink-account-consumer',
    'scan.startup.mode' = 'latest-offset',
    'format' = 'json',
    'json.fail-on-missing-field' = 'false',
    'json.ignore-parse-errors' = 'true'
);

CREATE TABLE clickhouse_account_sink (
    mid BIGINT,
    mid_str STRING,
    name STRING,
    sex STRING,
    sign STRING,
    face STRING,
    `rank` STRING,
    level INT,
    birthday STRING,
    vip_type INT,
    vip_status INT,
    vip_due_date BIGINT,
    vip_label_text STRING,
    vip_theme_type INT,
    vip_nickname_color STRING,
    vip_role INT,
    official_role INT,
    official_title STRING,
    official_desc STRING,
    official_type INT,
    pendant_pid INT,
    pendant_name STRING,
    nameplate_nid INT,
    nameplate_name STRING,
    nameplate_level STRING,
    nameplate_condition STRING,
    follower BIGINT,
    following INT,
    archive_count INT,
    article_count INT,
    like_num BIGINT,
    is_senior_member INT
) WITH (
    'connector' = 'jdbc',
    'url' = 'jdbc:mysql://clickhouse:9004/biliclaw?useSSL=false&allowPublicKeyRetrieval=true',
    'table-name' = 'dim_account',
    'driver' = 'com.mysql.cj.jdbc.Driver',
    'username' = 'default',
    'password' = '',
    'sink.buffer-flush.max-rows' = '10000',
    'sink.buffer-flush.interval' = '15s'
);

INSERT INTO clickhouse_account_sink
SELECT
    CAST(card.mid AS BIGINT),
    COALESCE(card.mid, ''),
    COALESCE(card.name, ''),
    COALESCE(card.sex, ''),
    COALESCE(card.sign, ''),
    COALESCE(card.face, ''),
    COALESCE(card.`rank`, ''),
    COALESCE(card.level_info.current_level, 0),
    COALESCE(card.birthday, ''),
    COALESCE(card.vip.vipType, COALESCE(card.vip.`type`, 0)),
    COALESCE(card.vip.vipStatus, COALESCE(card.vip.status, 0)),
    COALESCE(card.vip.due_date, 0),
    COALESCE(card.vip.label.text, ''),
    COALESCE(card.vip.theme_type, 0),
    COALESCE(card.vip.nickname_color, ''),
    COALESCE(card.vip.role, 0),
    COALESCE(card.Official.role, 0),
    COALESCE(card.Official.title, ''),
    COALESCE(card.Official.`desc`, COALESCE(card.official_verify.`desc`, '')),
    COALESCE(card.Official.`type`, COALESCE(card.official_verify.`type`, -1)),
    COALESCE(card.pendant.pid, 0),
    COALESCE(card.pendant.name, ''),
    COALESCE(card.nameplate.nid, 0),
    COALESCE(card.nameplate.name, ''),
    COALESCE(card.nameplate.level, ''),
    COALESCE(card.nameplate.`condition`, ''),
    CAST(COALESCE(follower, COALESCE(card.fans, 0)) AS BIGINT),
    COALESCE(card.attention, COALESCE(card.friend, 0)),
    COALESCE(archive_count, 0),
    COALESCE(article_count, 0),
    CAST(COALESCE(like_num, 0) AS BIGINT),
    COALESCE(card.is_senior_member, 0)
FROM kafka_account_source
WHERE card.mid IS NOT NULL;
