CREATE TABLE kafka_video_source (
    bvid STRING,
    aid BIGINT,
    videos INT,
    tid INT,
    tid_v2 INT,
    tname STRING,
    tname_v2 STRING,
    copyright INT,
    pic STRING,
    title STRING,
    pubdate INT,
    ctime INT,
    `desc` STRING,
    state INT,
    duration INT,
    `dynamic` STRING,
    dimension ROW<width INT, height INT, rotate INT>,
    `owner` ROW<mid BIGINT, name STRING, face STRING>,
    stat ROW<
        aid BIGINT,
        view BIGINT,
        danmaku INT,
        reply INT,
        favorite INT,
        coin INT,
        share INT,
        now_rank INT,
        his_rank INT,
        `like` INT,
        dislike INT
    >,
    rights ROW<
        bp INT,
        elec INT,
        download INT,
        movie INT,
        pay INT,
        hd5 INT,
        no_reprint INT,
        autoplay INT,
        ugc_pay INT,
        is_cooperation INT,
        ugc_pay_preview INT
    >,
    season_id BIGINT,
    is_story BOOLEAN,
    is_upower_exclusive BOOLEAN
) WITH (
    'connector' = 'kafka',
    'topic' = 'claw_video',
    'properties.bootstrap.servers' = 'kafka:29092',
    'properties.group.id' = 'flink-video-consumer',
    'scan.startup.mode' = 'latest-offset',
    'format' = 'json',
    'json.fail-on-missing-field' = 'false',
    'json.ignore-parse-errors' = 'true'
);

CREATE TABLE clickhouse_video_sink (
    bvid STRING,
    aid BIGINT,
    title STRING,
    `desc` STRING,
    pic STRING,
    duration INT,
    videos INT,
    tid INT,
    tid_v2 INT,
    tname STRING,
    tname_v2 STRING,
    pubdate INT,
    ctime INT,
    copyright INT,
    state INT,
    `dynamic` STRING,
    no_reprint INT,
    autoplay INT,
    download INT,
    is_cooperation INT,
    is_story INT,
    is_upower_exclusive INT,
    view_count BIGINT,
    danmaku_count INT,
    reply_count INT,
    favorite_count INT,
    coin_count INT,
    share_count INT,
    like_count INT,
    his_rank INT,
    now_rank INT,
    owner_mid BIGINT,
    owner_name STRING,
    owner_face STRING,
    season_id BIGINT,
    dimension_width INT,
    dimension_height INT,
    dimension_rotate INT
) WITH (
    'connector' = 'jdbc',
    'url' = 'jdbc:mysql://clickhouse:9004/biliclaw?useSSL=false&allowPublicKeyRetrieval=true',
    'table-name' = 'dim_video',
    'driver' = 'com.mysql.cj.jdbc.Driver',
    'username' = 'default',
    'password' = '',
    'sink.buffer-flush.max-rows' = '10000',
    'sink.buffer-flush.interval' = '15s'
);

INSERT INTO clickhouse_video_sink
SELECT
    bvid,
    aid,
    COALESCE(title, ''),
    COALESCE(`desc`, ''),
    COALESCE(pic, ''),
    COALESCE(duration, 0),
    COALESCE(videos, 1),
    COALESCE(tid, 0),
    COALESCE(tid_v2, 0),
    COALESCE(tname, ''),
    COALESCE(tname_v2, ''),
    COALESCE(pubdate, 0),
    COALESCE(ctime, 0),
    COALESCE(copyright, 0),
    COALESCE(state, 0),
    COALESCE(`dynamic`, ''),
    COALESCE(rights.no_reprint, 0),
    COALESCE(rights.autoplay, 0),
    COALESCE(rights.download, 0),
    COALESCE(rights.is_cooperation, 0),
    CASE WHEN is_story THEN 1 ELSE 0 END,
    CASE WHEN is_upower_exclusive THEN 1 ELSE 0 END,
    COALESCE(stat.view, 0),
    COALESCE(stat.danmaku, 0),
    COALESCE(stat.reply, 0),
    COALESCE(stat.favorite, 0),
    COALESCE(stat.coin, 0),
    COALESCE(stat.share, 0),
    COALESCE(stat.`like`, 0),
    COALESCE(stat.his_rank, 0),
    COALESCE(stat.now_rank, 0),
    COALESCE(`owner`.mid, 0),
    COALESCE(`owner`.name, ''),
    COALESCE(`owner`.face, ''),
    COALESCE(season_id, 0),
    COALESCE(dimension.width, 0),
    COALESCE(dimension.height, 0),
    COALESCE(dimension.rotate, 0)
FROM kafka_video_source
WHERE bvid IS NOT NULL AND aid IS NOT NULL;
