CREATE TABLE kafka_comment_source (
    rpid BIGINT,
    oid BIGINT,
    `type` INT,
    mid BIGINT,
    root BIGINT,
    parent BIGINT,
    dialog BIGINT,
    `count` INT,
    rcount INT,
    state INT,
    fansgrade INT,
    attr INT,
    ctime INT,
    mid_str STRING,
    oid_str STRING,
    rpid_str STRING,
    root_str STRING,
    parent_str STRING,
    dialog_str STRING,
    `like` INT,
    action INT,
    `member` ROW<
        mid STRING,
        uname STRING,
        sex STRING,
        sign STRING,
        avatar STRING,
        `rank` STRING,
        is_senior_member INT,
        level_info ROW<current_level INT>,
        pendant ROW<pid INT, name STRING>,
        nameplate ROW<nid INT, name STRING, level STRING>,
        official_verify ROW<`type` INT, `desc` STRING>,
        vip ROW<
            vipType INT,
            vipStatus INT,
            vipDueDate BIGINT,
            themeType INT,
            label ROW<text STRING>,
            nickname_color STRING
        >,
        user_sailing ROW<
            cardbg ROW<
                id INT,
                name STRING,
                fan ROW<is_fan INT, number INT, name STRING>
            >
        >,
        is_contractor BOOLEAN,
        contract_desc STRING
    >,
    content ROW<
        message STRING,
        max_line INT
    >,
    up_action ROW<
        `like` BOOLEAN,
        reply BOOLEAN
    >,
    invisible BOOLEAN,
    reply_control ROW<
        sub_reply_entry_text STRING,
        sub_reply_title_text STRING,
        time_desc STRING,
        support_share BOOLEAN
    >,
    folder ROW<
        has_folded BOOLEAN,
        is_folded BOOLEAN
    >
) WITH (
    'connector' = 'kafka',
    'topic' = 'claw_comment',
    'properties.bootstrap.servers' = 'kafka:29092',
    'properties.group.id' = 'flink-comment-consumer',
    'scan.startup.mode' = 'latest-offset',
    'format' = 'json',
    'json.fail-on-missing-field' = 'false',
    'json.ignore-parse-errors' = 'true'
);

CREATE TABLE clickhouse_comment_sink (
    rpid BIGINT,
    rpid_str STRING,
    oid BIGINT,
    oid_str STRING,
    `type` INT,
    root BIGINT,
    root_str STRING,
    parent BIGINT,
    parent_str STRING,
    dialog BIGINT,
    dialog_str STRING,
    `count` INT,
    rcount INT,
    `like` INT,
    state INT,
    attr INT,
    fansgrade INT,
    action INT,
    ctime INT,
    content_message STRING,
    content_max_line INT,
    mid BIGINT,
    mid_str STRING,
    member_uname STRING,
    member_sex STRING,
    member_sign STRING,
    member_avatar STRING,
    member_rank STRING,
    member_level INT,
    member_is_senior_member INT,
    member_vip_type INT,
    member_vip_status INT,
    member_vip_due_date BIGINT,
    member_vip_label_text STRING,
    member_vip_theme_type INT,
    member_nickname_color STRING,
    member_official_type INT,
    member_official_desc STRING,
    member_pendant_pid INT,
    member_pendant_name STRING,
    member_nameplate_nid INT,
    member_nameplate_name STRING,
    member_nameplate_level STRING,
    member_sailing_cardbg_id INT,
    member_sailing_cardbg_name STRING,
    member_sailing_fan_is_fan INT,
    member_sailing_fan_number INT,
    member_sailing_fan_name STRING,
    member_is_contractor INT,
    member_contract_desc STRING,
    up_action_like INT,
    up_action_reply INT,
    reply_control_sub_reply_entry_text STRING,
    reply_control_sub_reply_title_text STRING,
    reply_control_time_desc STRING,
    folder_has_folded INT,
    folder_is_folded INT,
    invisible INT,
    reply_control_support_share INT
) WITH (
    'connector' = 'jdbc',
    'url' = 'jdbc:mysql://clickhouse:9004/biliclaw?useSSL=false&allowPublicKeyRetrieval=true',
    'table-name' = 'dim_comment',
    'driver' = 'com.mysql.cj.jdbc.Driver',
    'username' = 'default',
    'password' = '',
    'sink.buffer-flush.max-rows' = '10000',
    'sink.buffer-flush.interval' = '15s'
);

INSERT INTO clickhouse_comment_sink
SELECT
    rpid,
    COALESCE(rpid_str, CAST(rpid AS STRING)),
    oid,
    COALESCE(oid_str, CAST(oid AS STRING)),
    COALESCE(`type`, 1),
    COALESCE(root, 0),
    COALESCE(root_str, '0'),
    COALESCE(parent, 0),
    COALESCE(parent_str, '0'),
    COALESCE(dialog, 0),
    COALESCE(dialog_str, '0'),
    COALESCE(`count`, 0),
    COALESCE(rcount, 0),
    COALESCE(`like`, 0),
    COALESCE(state, 0),
    COALESCE(attr, 0),
    COALESCE(fansgrade, 0),
    COALESCE(action, 0),
    COALESCE(ctime, 0),
    COALESCE(content.message, ''),
    COALESCE(content.max_line, 6),
    mid,
    COALESCE(mid_str, CAST(mid AS STRING)),
    COALESCE(`member`.uname, ''),
    COALESCE(`member`.sex, ''),
    COALESCE(`member`.sign, ''),
    COALESCE(`member`.avatar, ''),
    COALESCE(`member`.`rank`, ''),
    COALESCE(`member`.level_info.current_level, 0),
    COALESCE(`member`.is_senior_member, 0),
    COALESCE(`member`.vip.vipType, 0),
    COALESCE(`member`.vip.vipStatus, 0),
    COALESCE(`member`.vip.vipDueDate, 0),
    COALESCE(`member`.vip.label.text, ''),
    COALESCE(`member`.vip.themeType, 0),
    COALESCE(`member`.vip.nickname_color, ''),
    COALESCE(`member`.official_verify.`type`, -1),
    COALESCE(`member`.official_verify.`desc`, ''),
    COALESCE(`member`.pendant.pid, 0),
    COALESCE(`member`.pendant.name, ''),
    COALESCE(`member`.nameplate.nid, 0),
    COALESCE(`member`.nameplate.name, ''),
    COALESCE(`member`.nameplate.level, ''),
    COALESCE(`member`.user_sailing.cardbg.id, 0),
    COALESCE(`member`.user_sailing.cardbg.name, ''),
    COALESCE(`member`.user_sailing.cardbg.fan.is_fan, 0),
    COALESCE(`member`.user_sailing.cardbg.fan.number, 0),
    COALESCE(`member`.user_sailing.cardbg.fan.name, ''),
    CASE WHEN `member`.is_contractor THEN 1 ELSE 0 END,
    COALESCE(`member`.contract_desc, ''),
    CASE WHEN up_action.`like` THEN 1 ELSE 0 END,
    CASE WHEN up_action.reply THEN 1 ELSE 0 END,
    COALESCE(reply_control.sub_reply_entry_text, ''),
    COALESCE(reply_control.sub_reply_title_text, ''),
    COALESCE(reply_control.time_desc, ''),
    CASE WHEN folder.has_folded THEN 1 ELSE 0 END,
    CASE WHEN folder.is_folded THEN 1 ELSE 0 END,
    CASE WHEN invisible THEN 1 ELSE 0 END,
    CASE WHEN reply_control.support_share THEN 1 ELSE 0 END
FROM kafka_comment_source
WHERE rpid IS NOT NULL AND oid IS NOT NULL;
