INSERT INTO biliclaw.bilibili_comment_wide
SELECT
    c.rpid AS rpid,
    c.rpid_str AS rpid_str,
    c.oid AS oid,
    c.oid_str AS oid_str,
    c.`type` AS comment_type,
    c.root AS root_id,
    c.root_str AS root_id_str,
    c.parent AS parent_id,
    c.parent_str AS parent_id_str,
    c.dialog AS dialog_id,
    c.dialog_str AS dialog_id_str,
    CASE WHEN c.root = 0 THEN 1 ELSE 2 END AS comment_level,
    c.`count` AS reply_count,
    c.rcount AS reply_count_display,
    c.`like` AS like_count,
    c.state AS state,
    c.attr AS attr,
    c.fansgrade AS fansgrade,
    c.action AS action,
    c.up_action_like AS is_up_liked,
    c.up_action_reply AS is_up_replied,
    c.ctime AS comment_ctime,
    toDateTime(c.ctime) AS comment_ctime_dt,
    c.reply_control_time_desc AS comment_time_desc,
    c.content_message AS content_message,
    length(c.content_message) AS content_message_length,
    c.content_max_line AS content_max_line,
    0 AS has_jump_url,
    0 AS jump_url_count,
    0 AS at_user_count,
    c.reply_control_sub_reply_entry_text AS sub_reply_entry_text,
    c.reply_control_sub_reply_title_text AS sub_reply_title_text,
    c.folder_has_folded AS has_folded,
    c.folder_is_folded AS is_folded,
    c.invisible AS is_invisible,
    c.reply_control_support_share AS support_share,

    c.mid AS commenter_mid,
    c.mid_str AS commenter_mid_str,
    c.member_uname AS commenter_name,
    c.member_sex AS commenter_sex,
    c.member_sign AS commenter_sign,
    c.member_avatar AS commenter_avatar,
    c.member_rank AS commenter_rank,
    c.member_level AS commenter_level,
    c.member_is_senior_member AS commenter_is_senior_member,
    c.member_vip_type AS commenter_vip_type,
    c.member_vip_status AS commenter_vip_status,
    c.member_vip_due_date AS commenter_vip_due_date,
    c.member_vip_label_text AS commenter_vip_label,
    c.member_vip_theme_type AS commenter_vip_theme_type,
    c.member_nickname_color AS commenter_nickname_color,
    c.member_official_type AS commenter_official_type,
    c.member_official_desc AS commenter_official_desc,
    c.member_pendant_pid AS commenter_pendant_id,
    c.member_pendant_name AS commenter_pendant_name,
    c.member_nameplate_nid AS commenter_nameplate_id,
    c.member_nameplate_name AS commenter_nameplate_name,
    c.member_nameplate_level AS commenter_nameplate_level,
    c.member_sailing_cardbg_id AS commenter_sailing_cardbg_id,
    c.member_sailing_cardbg_name AS commenter_sailing_cardbg_name,
    c.member_sailing_fan_is_fan AS commenter_sailing_fan_is_fan,
    c.member_sailing_fan_number AS commenter_sailing_fan_number,
    c.member_sailing_fan_name AS commenter_sailing_fan_name,
    c.member_is_contractor AS commenter_is_contractor,
    c.member_contract_desc AS commenter_contract_desc,
    COALESCE(ca.follower, 0) AS commenter_follower_count,
    COALESCE(ca.following, 0) AS commenter_following_count,
    COALESCE(ca.archive_count, 0) AS commenter_archive_count,
    COALESCE(ca.article_count, 0) AS commenter_article_count,
    COALESCE(ca.like_num, 0) AS commenter_like_num,
    0 AS parent_reply_member_mid,
    '' AS parent_reply_member_name,
    v.bvid AS video_bvid,
    v.aid AS video_aid,
    v.title AS video_title,
    length(v.title) AS video_title_length,
    v.`desc` AS video_desc,
    length(v.`desc`) AS video_desc_length,
    v.pic AS video_pic,
    v.duration AS video_duration,
    v.videos AS video_videos_count,
    v.tid AS video_tid,
    v.tid_v2 AS video_tid_v2,
    v.tname AS video_tname,
    v.tname_v2 AS video_tname_v2,
    v.pubdate AS video_pubdate,
    toDateTime(v.pubdate) AS video_pubdate_dt,
    v.ctime AS video_ctime,
    toDateTime(v.ctime) AS video_ctime_dt,
    v.copyright AS video_copyright,
    v.state AS video_state,
    v.is_cooperation AS video_is_cooperation,
    v.is_story AS video_is_story,
    v.is_upower_exclusive AS video_is_upower_exclusive,
    v.no_reprint AS video_no_reprint,
    v.autoplay AS video_autoplay,
    v.download AS video_download,
    v.view_count AS video_view_count,
    v.danmaku_count AS video_danmaku_count,
    v.reply_count AS video_reply_count,
    v.favorite_count AS video_favorite_count,
    v.coin_count AS video_coin_count,
    v.share_count AS video_share_count,
    v.like_count AS video_like_count,
    v.his_rank AS video_his_rank,
    v.now_rank AS video_now_rank,
    v.season_id AS video_season_id,
    '' AS video_season_title,
    0 AS video_season_ep_count,
    0 AS video_mission_id,
    v.dimension_width AS video_dimension_width,
    v.dimension_height AS video_dimension_height,
    v.dimension_rotate AS video_dimension_rotate,
    v.owner_mid AS up_mid,
    v.owner_name AS up_name,
    v.owner_face AS up_face,
    COALESCE(a.sex, '') AS up_sex,
    COALESCE(a.sign, '') AS up_sign,
    COALESCE(a.level, 0) AS up_level,
    COALESCE(a.`rank`, '') AS up_rank,
    COALESCE(a.vip_type, 0) AS up_vip_type,
    COALESCE(a.vip_status, 0) AS up_vip_status,
    COALESCE(a.vip_due_date, 0) AS up_vip_due_date,
    COALESCE(a.official_role, 0) AS up_official_role,
    COALESCE(a.official_title, '') AS up_official_title,
    COALESCE(a.official_type, -1) AS up_official_type,
    COALESCE(a.pendant_pid, 0) AS up_pendant_id,
    COALESCE(a.pendant_name, '') AS up_pendant_name,
    COALESCE(a.nameplate_nid, 0) AS up_nameplate_id,
    COALESCE(a.nameplate_name, '') AS up_nameplate_name,
    COALESCE(a.nameplate_level, '') AS up_nameplate_level,
    COALESCE(a.follower, 0) AS up_follower_count,
    COALESCE(a.following, 0) AS up_following_count,
    COALESCE(a.archive_count, 0) AS up_archive_count,
    COALESCE(a.article_count, 0) AS up_article_count,
    COALESCE(a.like_num, 0) AS up_like_num,
    COALESCE(a.is_senior_member, 0) AS up_is_senior_member,
    toDate(c.ctime) AS comment_date,
    toHour(toDateTime(c.ctime)) AS comment_hour,
    toDayOfWeek(toDateTime(c.ctime)) AS comment_day_of_week,
    toDate(v.pubdate) AS video_publish_date,
    dateDiff('day', toDateTime(v.pubdate), toDateTime(c.ctime)) AS comment_video_interval_days,
    dateDiff('hour', toDateTime(v.pubdate), toDateTime(c.ctime)) AS comment_video_interval_hours,
    CASE WHEN c.root = 0 THEN 1 ELSE 0 END AS is_top_level_comment,
    CASE WHEN c.`count` > 0 THEN 1 ELSE 0 END AS has_replies,
    CASE WHEN c.mid = v.owner_mid THEN 1 ELSE 0 END AS is_commenter_up,
    CASE WHEN c.member_vip_status = 1 THEN 1 ELSE 0 END AS is_commenter_vip,
    CASE WHEN COALESCE(a.vip_status, 0) = 1 THEN 1 ELSE 0 END AS is_up_vip,
    'bilibili_spider' AS data_source,
    now() AS etl_time,
    '1.0' AS data_version,
    v.topic_keyword AS topic_keyword
FROM biliclaw.dim_comment AS c
LEFT JOIN biliclaw.dim_video AS v ON c.oid = v.aid
LEFT JOIN biliclaw.dim_account AS a ON v.owner_mid = a.mid
LEFT JOIN biliclaw.dim_account AS ca ON c.mid = ca.mid
SETTINGS max_partitions_per_insert_block = 0;
